import { 
  BankAccount, 
  BankCard, 
  Beneficiary, 
  BankTransaction, 
  BillItem, 
  SpendingAnalytics, 
  RiskAssessment, 
  UserTransactionLimit 
} from '@/types/banking';

export const DEFAULT_USER_TRANSACTION_LIMIT: UserTransactionLimit = {
  warningThreshold: 5000,
  enabled: true,
  currency: 'INR',
  lastUpdated: new Date().toISOString(),
};

export const MOCK_BANK_ACCOUNT: BankAccount = {
  accountNumber: '123456782734',
  maskedAccountNumber: '•••• 2734',
  accountHolderName: 'Yashwanth Gowda',
  availableBalance: 38729.61,
  currency: 'INR',
  accountType: 'Savings',
  ifscCode: 'NAYN0004821',
  averageTransactionAmount: 850.0,
  userConfiguredLimit: 5000,
};

export const MOCK_SECONDARY_ACCOUNT: BankAccount = {
  accountNumber: '987654328812',
  maskedAccountNumber: '•••• 8812',
  accountHolderName: 'Yashwanth Gowda',
  availableBalance: 13909.31,
  currency: 'INR',
  accountType: 'Current',
  ifscCode: 'NAYN0004822',
  averageTransactionAmount: 2500.0,
};

export const MOCK_PRIMARY_CARD: BankCard = {
  id: 'card-1',
  cardNumber: '4821 7890 2411 2734',
  maskedCardNumber: '••••  ••••  ••••  2734',
  cardHolderName: 'YASHWANTH GOWDA',
  expiryDate: '08/28',
  cvv: '392',
  cardType: 'VISA',
  network: 'Visa Platinum',
  bankName: 'Debit Card',
  isFrozen: false,
  isContactless: true,
  dailyLimit: 50000,
};

export const MOCK_BENEFICIARIES: Beneficiary[] = [
  {
    id: 'ben-rohan',
    name: 'Rohan Sharma',
    nameKannada: 'ರೋಹನ್ ಶರ್ಮಾ',
    nameHindi: 'रोहन शर्मा',
    accountNumber: '582910482911',
    maskedAccountNumber: '•••• 2911',
    upiId: 'rohan@okaxis',
    relation: 'Friend / Team',
    frequentlyUsed: true,
    avatarColor: 'bg-[#4F46E5]',
    colorHex: '#4F46E5',
  },
  {
    id: 'ben-ramesh',
    name: 'Ramesh Kumar',
    nameKannada: 'ರಮೇಶ್ ಕುಮಾರ್',
    nameHindi: 'रमेश कुमार',
    accountNumber: '123456781234',
    maskedAccountNumber: '•••• 1234',
    upiId: 'ramesh@upi',
    relation: 'Family Member',
    frequentlyUsed: true,
    avatarColor: 'bg-[#2563EB]',
    colorHex: '#2563EB',
  },
  {
    id: 'ben-suresh',
    name: 'Suresh Patil',
    nameKannada: 'ಸುರೇಶ್ ಪಾಟೀಲ್',
    nameHindi: 'सुरेश पाटिल',
    accountNumber: '987654326721',
    maskedAccountNumber: '•••• 6721',
    upiId: 'suresh@okaxis',
    relation: 'Colleague',
    frequentlyUsed: true,
    avatarColor: 'bg-[#059669]',
    colorHex: '#059669',
  },
  {
    id: 'ben-priya',
    name: 'Priya Sharma',
    nameKannada: 'ಪ್ರಿಯಾ ಶರ್ಮಾ',
    nameHindi: 'प्रिया शर्मा',
    accountNumber: '456789129012',
    maskedAccountNumber: '•••• 9012',
    upiId: 'priya@okhdfc',
    relation: 'Sister',
    frequentlyUsed: true,
    avatarColor: 'bg-[#7C3AED]',
    colorHex: '#7C3AED',
  },
  {
    id: 'ben-ralph',
    name: 'Ralph Edwards',
    nameKannada: 'ರಾಲ್ಫ್ ಎಡ್ವರ್ಡ್ಸ್',
    nameHindi: 'राल्फ एडवर्ड्स',
    accountNumber: '334190827119',
    maskedAccountNumber: '•••• 7119',
    upiId: 'ralph@icici',
    relation: 'Business Associate',
    frequentlyUsed: false,
    avatarColor: 'bg-[#D97706]',
    colorHex: '#D97706',
  },
  {
    id: 'ben-jerome',
    name: 'Jerome Bell',
    nameKannada: 'ಜೆರೋಮ್ ಬೆಲ್',
    nameHindi: 'जेरोम बेल',
    accountNumber: '789012343341',
    maskedAccountNumber: '•••• 3341',
    upiId: 'jerome@paytm',
    relation: 'Designer',
    frequentlyUsed: false,
    avatarColor: 'bg-[#E11D48]',
    colorHex: '#E11D48',
  },
  {
    id: 'ben-maya',
    name: 'Maya Devi',
    nameKannada: 'ಮಾಯಾ ದೇವಿ',
    nameHindi: 'माया देवी',
    accountNumber: '882190342210',
    maskedAccountNumber: '•••• 2210',
    upiId: 'maya@upi',
    relation: 'Manager',
    frequentlyUsed: true,
    avatarColor: 'bg-[#0D9488]',
    colorHex: '#0D9488',
  },
  {
    id: 'ben-alex',
    name: 'Alex Turner',
    nameKannada: 'ಅಲೆಕ್ಸ್ ಟರ್ನರ್',
    nameHindi: 'एलेक्स टर्नर',
    accountNumber: '671209384451',
    maskedAccountNumber: '•••• 4451',
    upiId: 'alex@axis',
    relation: 'Partner',
    frequentlyUsed: false,
    avatarColor: 'bg-violet-600',
  },
];

export const MOCK_TRANSACTIONS: BankTransaction[] = [
  {
    id: 'tx-apple',
    title: 'Apple Services',
    titleKannada: 'ಆಪಲ್ ಸೇವೆಗಳು',
    titleHindi: 'एप्पल सर्विसेज',
    merchant: 'Apple Media Services',
    category: 'entertainment',
    amount: 653.0,
    type: 'debit',
    timestamp: 'Today, 10:45 AM',
    dateFormatted: '22 Aug 2026',
    status: 'completed',
    recipientOrSource: 'Apple Subscription',
    paymentMethod: 'Card •••• 2734',
    referenceId: 'NAYAN-APL-94821',
    note: 'iCloud + Music Subscription',
  },
  {
    id: 'tx-swiggy',
    title: 'Swiggy Food',
    titleKannada: 'ಸ್ವಿಗ್ಗಿ ಫುಡ್',
    titleHindi: 'स्विगी फूड',
    merchant: 'Swiggy Delivery',
    category: 'food',
    amount: 842.0,
    type: 'debit',
    timestamp: 'Yesterday, 08:15 PM',
    dateFormatted: '21 Aug 2026',
    status: 'completed',
    recipientOrSource: 'Bhojanam Express',
    paymentMethod: 'UPI Auto-pay',
    referenceId: 'UPI-SWG-77491',
    note: 'Family Dinner',
  },
  {
    id: 'tx-ralph',
    title: 'Ralph Edwards',
    titleKannada: 'ರಾಲ್ಫ್ ಎಡ್ವರ್ಡ್ಸ್',
    titleHindi: 'राल्फ एडवर्ड्स',
    merchant: 'Ralph Edwards',
    category: 'transfer',
    amount: 2643.0,
    type: 'credit',
    timestamp: '20 Aug 2026, 03:30 PM',
    dateFormatted: '20 Aug 2026',
    status: 'completed',
    recipientOrSource: 'Ralph Edwards',
    paymentMethod: 'IMPS Bank Transfer',
    referenceId: 'IMPS-TX-88301',
    note: 'Project Design Split',
  },
  {
    id: 'tx-jerome',
    title: 'Jerome Bell',
    titleKannada: 'ಜೆರೋಮ್ ಬೆಲ್',
    titleHindi: 'जेरोम बेल',
    merchant: 'Jerome Bell',
    category: 'transfer',
    amount: 520.0,
    type: 'debit',
    timestamp: '19 Aug 2026, 11:20 AM',
    dateFormatted: '19 Aug 2026',
    status: 'completed',
    recipientOrSource: 'Jerome Bell',
    paymentMethod: 'UPI Direct',
    referenceId: 'UPI-JRM-11204',
    note: 'Coffee & Snacks',
  },
  {
    id: 'tx-bescom',
    title: 'BESCOM Electricity',
    titleKannada: 'ವಿದ್ಯುತ್ ಬಿಲ್ ಪಾವತಿ',
    titleHindi: 'बिजली बिल भुगतान',
    merchant: 'BESCOM Karnataka',
    category: 'utility',
    amount: 1240.0,
    type: 'debit',
    timestamp: '18 Aug 2026, 04:15 PM',
    dateFormatted: '18 Aug 2026',
    status: 'completed',
    recipientOrSource: 'BESCOM Karnataka',
    paymentMethod: 'BBPS BillPay',
    referenceId: 'BBPS-BSC-49210',
    note: 'Monthly Home Electricity Bill',
  },
  {
    id: 'tx-salary',
    title: 'Monthly Salary Credit',
    titleKannada: 'ಮಾಸಿಕ ವೇತನ ಜಮಾ',
    titleHindi: 'मासिक वेतन क्रेडिट',
    merchant: 'TechCorp India',
    category: 'salary',
    amount: 48000.0,
    type: 'credit',
    timestamp: '01 Aug 2026, 09:00 AM',
    dateFormatted: '01 Aug 2026',
    status: 'completed',
    recipientOrSource: 'TechCorp India Pvt Ltd',
    paymentMethod: 'NEFT Corporate Salary',
    referenceId: 'NEFT-SAL-10029',
    note: 'August 2026 Payroll',
  },
];

export const MOCK_BILLS: BillItem[] = [
  {
    id: 'bill-elec',
    title: 'Electricity Bill',
    category: 'electricity',
    billerName: 'BESCOM Bangalore',
    amount: 1240.0,
    dueDate: 'Due today',
    isDueToday: true,
    consumerNumber: 'BES-849201',
    status: 'unpaid',
  },
  {
    id: 'bill-mob',
    title: 'Mobile Postpaid',
    category: 'mobile',
    billerName: 'Jio Prepaid / Postpaid',
    amount: 299.0,
    dueDate: 'Due in 3 days',
    consumerNumber: '9876543210',
    status: 'unpaid',
  },
  {
    id: 'bill-net',
    title: 'Fiber Internet',
    category: 'internet',
    billerName: 'ACT Fibernet',
    amount: 1050.0,
    dueDate: 'Due in 5 days',
    consumerNumber: 'ACT-BLR-9921',
    status: 'unpaid',
  },
  {
    id: 'bill-wtr',
    title: 'Water Supply',
    category: 'water',
    billerName: 'BWSSB Bangalore',
    amount: 420.0,
    dueDate: 'Due in 8 days',
    consumerNumber: 'WTR-448201',
    status: 'unpaid',
  },
];

export const MOCK_SPENDING_ANALYTICS: SpendingAnalytics = {
  monthName: 'August 2026',
  totalIncome: 50643.0,
  totalExpense: 11913.39,
  spentPercentage: 60,
  savedPercentage: 40,
  foodExpenseIncreasePct: 18,
  categories: [
    { id: 'cat-food', name: 'Food & Dining', nameKannada: 'ಆಹಾರ & ಊಟ', nameHindi: 'भोजन और खान-पान', amount: 6420, percentage: 38, color: '#3B82F6', trend: '+18% vs usual' },
    { id: 'cat-shopping', name: 'Shopping', nameKannada: 'ಶಾಪಿಂಗ್', nameHindi: 'खरीदारी', amount: 4200, percentage: 25, color: '#8B5CF6', trend: '-5% vs usual' },
    { id: 'cat-bills', name: 'Bills & Utilities', nameKannada: 'ಬಿಲ್‌ಗಳು', nameHindi: 'बिल और उपयोगिताएं', amount: 3850, percentage: 22, color: '#10B981', trend: 'Stable' },
    { id: 'cat-transport', name: 'Transport & Cab', nameKannada: 'ಸಾರಿಗೆ', nameHindi: 'परिवहन', amount: 1900, percentage: 11, color: '#F59E0B', trend: '-2% vs usual' },
    { id: 'cat-edu', name: 'Education & Learning', nameKannada: 'ಶಿಕ್ಷಣ', nameHindi: 'शिक्षा', amount: 2500, percentage: 14, color: '#EC4899', trend: 'Normal' },
  ],
  monthlyHistory: [
    { month: 'Nov', amount: 28400 },
    { month: 'Dec', amount: 34100 },
    { month: 'Jan', amount: 31200 },
    { month: 'Feb', amount: 36500 },
    { month: 'Mar', amount: 38729 },
  ],
};

/**
 * Deterministic Adaptive Friction & User-Configured Limit Evaluation Engine
 */
export function evaluateTransferRisk(
  amount: number, 
  recipientName: string, 
  userConfiguredLimit: number = 5000
): RiskAssessment {
  const avg = MOCK_BANK_ACCOUNT.averageTransactionAmount;
  const multiplier = Number((amount / avg).toFixed(1));
  const isLimitExceeded = amount > userConfiguredLimit;
  const exceededBy = isLimitExceeded ? amount - userConfiguredLimit : 0;

  // 1. Hard maximum single transaction cap
  if (amount > 100000) {
    return {
      level: 'blocked',
      multiplier,
      averageAmount: avg,
      requestedAmount: amount,
      configuredLimit: userConfiguredLimit,
      isLimitExceeded: true,
      exceededBy: amount - userConfiguredLimit,
      warningTitle: 'Transaction Exceeds Maximum Bank Limit',
      warningTitleKannada: 'ವಹಿವಾಟು ಗರಿಷ್ಠ ಬ್ಯಾಂಕ್ ಮಿತಿಯನ್ನು ಮೀರಿದೆ',
      warningTitleHindi: 'लेनदेन अधिकतम बैंक सीमा से अधिक है',
      warningDescription: 'For your security, single online transfers are capped at ₹1,00,000.',
      warningDescriptionKannada: 'ನಿಮ್ಮ ಸುರಕ್ಷತೆಗಾಗಿ ಆನ್‌ಲೈನ್ ವರ್ಗಾವಣೆ ಮಿತಿ ₹1,00,000 ಆಗಿದೆ.',
      warningDescriptionHindi: 'आपकी सुरक्षा के लिए अधिकतम सीमा ₹1,00,000 है।',
      reasons: ['Amount exceeds maximum permitted single transaction threshold.'],
      reasonsKannada: ['ಗರಿಷ್ಠ ಅನುಮತಿಸಲಾದ ವಹಿವಾಟು ಮಿತಿ ಮೀರಿದೆ.'],
      reasonsHindi: ['अधिकतम अनुमत सीमा पार हो गई है।'],
      requiresAdditionalConfirmation: true,
      allowContinue: false,
    };
  }

  // 2. User-Configured Safety Threshold Exceeded Check
  if (isLimitExceeded) {
    return {
      level: 'elevated',
      multiplier,
      averageAmount: avg,
      requestedAmount: amount,
      configuredLimit: userConfiguredLimit,
      isLimitExceeded: true,
      exceededBy,
      warningTitle: 'Transaction Limit Exceeded',
      warningTitleKannada: 'ವಹಿವಾಟು ಮಿತಿ ಮೀರಿದೆ',
      warningTitleHindi: 'लेनदेन सीमा पार हो गई है',
      warningDescription: `You're attempting to send ₹${amount.toLocaleString('en-IN')}. Your warning limit is ₹${userConfiguredLimit.toLocaleString('en-IN')}. This transaction is above the limit you configured for additional verification.`,
      warningDescriptionKannada: `ನೀವು ₹${amount.toLocaleString('en-IN')} ಕಳುಹಿಸಲು ಪ್ರಯತ್ನಿಸುತ್ತಿದ್ದೀರಿ. ನಿಮ್ಮ ಸುರಕ್ಷತಾ ಮಿತಿ ₹${userConfiguredLimit.toLocaleString('en-IN')} ಆಗಿದೆ. ಹೆಚ್ಚುವರಿ ಪರಿಶೀಲನೆ ಅಗತ್ಯವಿದೆ.`,
      warningDescriptionHindi: `आप ₹${amount.toLocaleString('en-IN')} भेजने का प्रयास कर रहे हैं। आपकी सुरक्षा सीमा ₹${userConfiguredLimit.toLocaleString('en-IN')} है। इसके लिए अतिरिक्त सत्यापन आवश्यक है।`,
      reasons: [
        `Amount (₹${amount.toLocaleString('en-IN')}) exceeds your configured safety threshold of ₹${userConfiguredLimit.toLocaleString('en-IN')}.`,
        `Recipient: ${recipientName}`,
        `Safety buffer: ₹${exceededBy.toLocaleString('en-IN')} above configured threshold.`,
      ],
      reasonsKannada: [
        `ಮೊತ್ತವು ನಿಮ್ಮ ಸುರಕ್ಷತಾ ಮಿತಿಯಾದ ₹${userConfiguredLimit.toLocaleString('en-IN')} ಗಿಂತ ₹${exceededBy.toLocaleString('en-IN')} ಹೆಚ್ಚಾಗಿದೆ.`,
        `ಸ್ವೀಕರಿಸುವವರು: ${recipientName}`,
      ],
      reasonsHindi: [
        `राशि आपकी सुरक्षा सीमा ₹${userConfiguredLimit.toLocaleString('en-IN')} से ₹${exceededBy.toLocaleString('en-IN')} अधिक है।`,
        `प्राप्तकर्ता: ${recipientName}`,
      ],
      requiresAdditionalConfirmation: true,
      allowContinue: true,
    };
  }

  // 3. Normal Spending Profile (Within Limit)
  return {
    level: 'standard',
    multiplier,
    averageAmount: avg,
    requestedAmount: amount,
    configuredLimit: userConfiguredLimit,
    isLimitExceeded: false,
    exceededBy: 0,
    warningTitle: 'Standard Payment Review',
    warningTitleKannada: 'ಸಾಮಾನ್ಯ ಪಾವತಿ ಪರಿಶೀಲನೆ',
    warningTitleHindi: 'सामान्य भुगतान समीक्षा',
    warningDescription: 'Transaction within your configured safety limit.',
    warningDescriptionKannada: 'ನಿಮ್ಮ ಕಾನ್ಫಿಗರ್ ಮಾಡಿದ ಸುರಕ್ಷತಾ ಮಿತಿಯಲ್ಲಿದೆ.',
    warningDescriptionHindi: 'आपकी निर्धारित सुरक्षा सीमा के भीतर लेनदेन।',
    reasons: [`Amount is within your configured threshold of ₹${userConfiguredLimit.toLocaleString('en-IN')}.`],
    reasonsKannada: [`ಮೊತ್ತವು ನಿಮ್ಮ ₹${userConfiguredLimit.toLocaleString('en-IN')} ಮಿತಿಯಲ್ಲಿದೆ.`],
    reasonsHindi: [`राशि आपकी ₹${userConfiguredLimit.toLocaleString('en-IN')} सीमा के भीतर है।`],
    requiresAdditionalConfirmation: false,
    allowContinue: true,
  };
}
