import { ServiceDefinition, PersonaPreset } from '@/types';

export const MOCK_SERVICES: ServiceDefinition[] = [
  {
    id: 'government-scholarship',
    title: 'National Post-Secondary Education Scholarship',
    titleKannada: 'ರಾಷ್ಟ್ರೀಯ ಉನ್ನತ ಶಿಕ್ಷಣ ವಿದ್ಯಾರ್ಥಿವೇತನ ಅರ್ಜಿಯನ್ನು ಭರ್ತಿ ಮಾಡಿ',
    titleHindi: 'राष्ट्रीय उच्च शिक्षा छात्रवृत्ति आवेदन',
    category: 'government',
    organization: 'Ministry of Education & Social Inclusion',
    description: 'Financial support grant for students pursuing higher education across accredited state institutions.',
    estimatedTime: '6 minutes',
    badge: 'Government Scheme',
    standardDenseNotice: 'Notice: Applicants must submit documentary evidence validating their eligibility under Section 12(B) of the Central Educational Code. Non-compliance results in automatic forfeiture.',
    steps: [
      {
        stepNumber: 1,
        totalSteps: 5,
        title: 'Full Name as per Official ID',
        titleKannada: 'ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರು (ಆಧಾರ್/ಐಡಿ ಪ್ರಕಾರ)',
        titleHindi: 'आपका पूरा नाम (सरकारी पहचान पत्र के अनुसार)',
        description: 'Provide your full legal name exactly as printed on your government-issued identity certificate.',
        descriptionKannada: 'ನಿಮ್ಮ ಸರ್ಕಾರಿ ಗುರುತಿನ ಚೀಟಿಯಲ್ಲಿರುವಂತೆ ನಿಮ್ಮ ಸಂಪೂರ್ಣ ಹೆಸರನ್ನು ಇಲ್ಲಿ ನಮೂದಿಸಿ.',
        descriptionHindi: 'अपने सरकारी पहचान पत्र पर छपा हुआ पूरा नाम दर्ज करें।',
        simplifiedDescription: 'What is your full legal name?',
        fieldLabel: 'Applicant Legal Full Name',
        fieldLabelKannada: 'ಅರ್ಜಿದಾರರ ಪೂರ್ಣ ಹೆಸರು',
        fieldLabelHindi: 'आवेदक का पूरा नाम',
        fieldType: 'text',
        placeholder: 'e.g. Ramesh Kumar',
        helpText: 'Ensure your spelling matches your National Identity document.',
        audioPrompt: 'Step 1: Please enter your full name as it appears on your official identity document.',
      },
      {
        stepNumber: 2,
        totalSteps: 5,
        title: 'Date of Birth & Gender Verification',
        titleKannada: 'ಹುಟ್ಟಿದ ದಿನಾಂಕ ಮತ್ತು ಲಿಂಗ',
        titleHindi: 'जन्म तिथि और लिंग सत्यापन',
        description: 'Enter your official date of birth as recorded in school matriculation registers.',
        descriptionKannada: 'ನಿಮ್ಮ ಶಾಲೆ ಅಥವಾ ಸರ್ಕಾರಿ ದಾಖಲೆಯಲ್ಲಿರುವಂತೆ ಹುಟ್ಟಿದ ದಿನಾಂಕವನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
        descriptionHindi: 'अपनी जन्म तिथि दर्ज करें।',
        simplifiedDescription: 'When were you born?',
        fieldLabel: 'Date of Birth (DD/MM/YYYY)',
        fieldLabelKannada: 'ಹುಟ್ಟಿದ ದಿನಾಂಕ',
        fieldLabelHindi: 'जन्म तिथि',
        fieldType: 'date',
        helpText: 'Select or type your birth date.',
        audioPrompt: 'Step 2: Enter your date of birth.',
      },
      {
        stepNumber: 3,
        totalSteps: 5,
        title: 'Annual Household Income Category',
        titleKannada: 'ಕುಟುಂಬದ ವಾರ್ಷಿಕ ಆದಾಯದ ವಿವರ',
        titleHindi: 'वार्षिक पारिवारिक आय श्रेणी',
        description: 'Specify cumulative family gross income before tax deductions for the current financial assessment year.',
        descriptionKannada: 'ನಿಮ್ಮ ಕುಟುಂಬದ ವರ್ಷದ ಒಟ್ಟು ಆದಾಯ ಎಷ್ಟು ಎಂಬುದನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
        descriptionHindi: 'अपने परिवार की वार्षिक आय चुनें।',
        simplifiedDescription: 'How much does your household earn in a year?',
        fieldLabel: 'Annual Household Income Bracket',
        fieldLabelKannada: 'ವಾರ್ಷಿಕ ಆದಾಯದ ಶ್ರೇಣಿ',
        fieldLabelHindi: 'वार्षिक आय सीमा',
        fieldType: 'select',
        options: [
          { value: 'under-1.5l', label: 'Below ₹1,500,000 per year', labelKannada: 'ವರ್ಷಕ್ಕೆ ₹1,50,000 ಗಿಂತ ಕಡಿಮೆ', labelHindi: '₹1,50,000 प्रति वर्ष से कम' },
          { value: '1.5l-3l', label: '₹1,500,000 - ₹3,000,000 per year', labelKannada: '₹1,50,000 ರಿಂದ ₹3,00,000', labelHindi: '₹1,50,000 से ₹3,00,000' },
          { value: 'above-3l', label: 'Above ₹3,000,000 per year', labelKannada: '₹3,00,000 ಗಿಂತ ಹೆಚ್ಚು', labelHindi: '₹3,00,000 से अधिक' },
        ],
        helpText: 'Scholarship priority is granted to households below threshold limits.',
        audioPrompt: 'Step 3: Select your household income range.',
      },
      {
        stepNumber: 4,
        totalSteps: 5,
        title: 'Upload Income Certificate',
        titleKannada: 'ಆದಾಯ ಪ್ರಮಾಣಪತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
        titleHindi: 'आय प्रमाण पत्र अपलोड करें',
        description: 'Submit an attested PDF or JPG copy of your official revenue authority income certificate.',
        descriptionKannada: 'ನಿಮ್ಮ ಗ್ರಾಮ ಪಂಚಾಯತಿ ಅಥವಾ ತಹಶೀಲ್ದಾರ್ ನೀಡಿದ ಆದಾಯ ಪ್ರಮಾಣಪತ್ರದ ಫೋಟೋವನ್ನು ಇಲ್ಲಿ ಹಾಕಿ.',
        descriptionHindi: 'अपना आय प्रमाण पत्र अपलोड करें।',
        simplifiedDescription: 'Upload a document that proves your household income.',
        fieldLabel: 'Income Certificate Document (PDF/Photo)',
        fieldLabelKannada: 'ಆದಾಯ ಪತ್ರದ ಫೋಟೋ / ಪಿಡಿಎಫ್',
        fieldLabelHindi: 'प्रमाण पत्र फ़ाइल',
        fieldType: 'file',
        helpText: 'You can tap to select file or take a clear camera photo.',
        audioPrompt: 'Step 4: Upload your income proof document.',
      },
      {
        stepNumber: 5,
        totalSteps: 5,
        title: 'Review & Submit Application',
        titleKannada: 'ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಸಲ್ಲಿಸಿ',
        titleHindi: 'समीक्षा करें और जमा करें',
        description: 'Verify all captured data points before initiating final submission to central database.',
        descriptionKannada: 'ನೀವು ನೀಡಿದ ಎಲ್ಲ ವಿವರಗಳು ಸರಿಯಾಗಿವೆಯೇ ಎಂದು ಪರಿಶೀಲಿಸಿ ಸಲ್ಲಿಸಿ ಬಟನ್ ಒತ್ತಿ.',
        descriptionHindi: 'अपने सभी विवरणों की जांच करें और सबमिट करें।',
        simplifiedDescription: 'Review your details and tap Submit.',
        fieldLabel: 'Final Declaration & Confirmation',
        fieldLabelKannada: 'ಉಲ್ಲೇಖ ದೃಢೀಕರಣ',
        fieldLabelHindi: 'अंतिम घोषणा',
        fieldType: 'radio',
        options: [
          { value: 'confirm', label: 'I confirm all information provided is accurate.', labelKannada: 'ನೀಡಿರುವ ಎಲ್ಲ ವಿವರಗಳು ನಿಜವೆಂದು ನಾನು ದೃಢೀಕರಿಸುತ್ತೇನೆ.', labelHindi: 'मैं पुष्टि करता हूं कि सभी जानकारी सही है।' }
        ],
        helpText: 'ANUKOOL will confirm your action before final sending.',
        audioPrompt: 'Step 5: Final review. Confirm your information and tap submit.',
      }
    ]
  },
  {
    id: 'healthcare-appointment',
    title: 'CityCare General Hospital Appointment Booking',
    titleKannada: 'ಸಿಟಿಕೇರ್ ಆಸ್ಪತ್ರೆಯ ವೈದ್ಯರ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕಿಂಗ್',
    titleHindi: 'सिटीकेयर अस्पताल डॉक्टर अपॉइंटमेंट',
    category: 'healthcare',
    organization: 'Department of Public Health & Clinical Services',
    description: 'Schedule outpatient consultation with specialized physicians at district care hospitals.',
    estimatedTime: '4 minutes',
    badge: 'Healthcare Service',
    standardDenseNotice: 'Outpatient Triage Protocol: Consultation slots are contingent upon emergency department priority. Patient must arrive 30 minutes prior with clinical history dossier.',
    steps: [
      {
        stepNumber: 1,
        totalSteps: 4,
        title: 'Select Medical Department / Specialty',
        titleKannada: 'ವೈದ್ಯಕೀಯ ವಿಭಾಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
        titleHindi: 'चिकित्सा विभाग चुनें',
        description: 'Specify clinical specialty department required for primary consultation.',
        descriptionKannada: 'ನಿಮಗೆ ಯಾವ ರೀತಿಯ ವೈದ್ಯರ ಸಲಹೆ ಬೇಕು ಎಂಬುದನ್ನು ಇಲ್ಲಿ ಆಯ್ಕೆಮಾಡಿ.',
        descriptionHindi: 'आपको किस डॉक्टर को दिखाना है, वह विभाग चुनें।',
        simplifiedDescription: 'Which doctor do you need to see?',
        fieldLabel: 'Specialty Department',
        fieldLabelKannada: 'ವೈದ್ಯರ ವಿಭಾಗ',
        fieldLabelHindi: 'विभाग',
        fieldType: 'select',
        options: [
          { value: 'general', label: 'General Medicine / Fever / Checkup', labelKannada: 'ಸಾಮಾನ್ಯ ಚಿಕಿತ್ಸೆ / ಜ್ವರ / ತಪಾಸಣೆ', labelHindi: 'सामान्य चिकित्सा / बुखार / जांच' },
          { value: 'eye', label: 'Ophthalmology (Eye Care)', labelKannada: 'ಕಣ್ಣಿನ ವೈದ್ಯರು (ನೇತ್ರ ಚಿಕಿತ್ಸೆ)', labelHindi: 'आंखों के डॉक्टर' },
          { value: 'ortho', label: 'Orthopedics (Bones & Joint Pain)', labelKannada: 'ಮೂಳೆ ಮತ್ತು ಕೀಲು ನೋವು', labelHindi: 'हड्डी और जोड़ विशेषज्ञ' },
          { value: 'cardio', label: 'Cardiology (Heart Care)', labelKannada: 'ಹೃದಯ ಸಂಬಂಧಿ ಚಿಕಿತ್ಸೆ', labelHindi: 'हृदय रोग विशेषज्ञ' },
        ],
        helpText: 'Select the department that best fits your symptom.',
        audioPrompt: 'Step 1: Choose the hospital department or specialist you wish to consult.',
      },
      {
        stepNumber: 2,
        totalSteps: 4,
        title: 'Patient Identification Number / Mobile',
        titleKannada: 'ರೋಗಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ಅಥವಾ ಆಸ್ಪತ್ರೆ ಐಡಿ',
        titleHindi: 'मरीज़ का मोबाइल नंबर या अस्पताल आईडी',
        description: 'Provide 10-digit primary contact phone number or registered hospital health card numeric identifier.',
        descriptionKannada: 'ನಿಮ್ಮ 10 ಅಂಗಳ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ.',
        descriptionHindi: 'अपना 10 अंकों का मोबाइल नंबर दर्ज करें।',
        simplifiedDescription: 'What is your mobile phone number?',
        fieldLabel: 'Primary Mobile Contact Number',
        fieldLabelKannada: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
        fieldLabelHindi: 'मोबाइल नंबर',
        fieldType: 'text',
        placeholder: 'e.g. 9876543210',
        helpText: 'We will send appointment confirmation SMS to this number.',
        audioPrompt: 'Step 2: Enter your 10-digit mobile phone number.',
      },
      {
        stepNumber: 3,
        totalSteps: 4,
        title: 'Preferred Appointment Date & Time Slot',
        titleKannada: 'ದಿನಾಂಕ ಮತ್ತು ಸಮಯವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
        titleHindi: 'पसंदीदा तारीख और समय चुनें',
        description: 'Select calendar date and morning/afternoon operational clinic slot for attendance.',
        descriptionKannada: 'ನೀವು ಆಸ್ಪತ್ರೆಗೆ ಬರಲು ಬಯಸುವ ದಿನಾಂಕ ಮತ್ತು ಸಮಯವನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
        descriptionHindi: 'अस्पताल जाने का समय और दिन चुनें।',
        simplifiedDescription: 'When do you want to visit the hospital?',
        fieldLabel: 'Preferred Visit Slot',
        fieldLabelKannada: 'ಭೇಟಿಯ ಸಮಯ',
        fieldLabelHindi: 'समय',
        fieldType: 'select',
        options: [
          { value: 'tomorrow-morning', label: 'Tomorrow Morning (9:00 AM - 12:00 PM)', labelKannada: 'ನಾಳೆ ಬೆಳಿಗ್ಗೆ (9:00 ರಿಂದ 12:00)', labelHindi: 'कल सुबह (9:00 से 12:00)' },
          { value: 'tomorrow-afternoon', label: 'Tomorrow Afternoon (2:00 PM - 5:00 PM)', labelKannada: 'ನಾಳೆ ಮಧ್ಯಾಹ್ನ (2:00 ರಿಂದ 5:00)', labelHindi: 'कल दोपहर (2:00 से 5:00)' },
          { value: 'weekend-morning', label: 'Saturday Morning (9:00 AM - 12:00 PM)', labelKannada: 'ಶನಿವಾರ ಬೆಳಿಗ್ಗೆ (9:00 ರಿಂದ 12:00)', labelHindi: 'शनिवार सुबह (9:00 से 12:00)' },
        ],
        helpText: 'Please arrive 15 minutes before your scheduled slot.',
        audioPrompt: 'Step 3: Select your preferred visit day and time.',
      },
      {
        stepNumber: 4,
        totalSteps: 4,
        title: 'Confirm Hospital Appointment',
        titleKannada: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಖಚಿತಪಡಿಸಿ',
        titleHindi: 'अपॉइंटमेंट की पुष्टि करें',
        description: 'Review clinical consultation selection and execute confirmation token generation.',
        descriptionKannada: 'ಎಲ್ಲ ವಿವರಗಳು ಸರಿಯಾಗಿವೆ ಎಂದು ಪರಿಶೀಲಿಸಿ ಬುಕ್ ಮಾಡಿ.',
        descriptionHindi: 'विवरण जांचें और बुक करें।',
        simplifiedDescription: 'Review your appointment and tap Confirm.',
        fieldLabel: 'Confirmation',
        fieldLabelKannada: 'ಬುಕಿಂಗ್ ದೃಢೀಕರಣ',
        fieldLabelHindi: 'बुक करें',
        fieldType: 'radio',
        options: [
          { value: 'confirm', label: 'Confirm appointment booking', labelKannada: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಖಚಿತಪಡಿಸಿ', labelHindi: 'अपॉइंटमेंट पक्का करें' }
        ],
        helpText: 'No payment is required for OPD general registration.',
        audioPrompt: 'Step 4: Review and confirm your appointment booking.',
      }
    ]
  },
  {
    id: 'banking-billpay',
    title: 'Anukool Cooperative Utility & Bill Payment',
    titleKannada: 'ನಯನ್ ಬ್ಯಾಂಕ್ ವಿದ್ಯುತ್ ಮತ್ತು ಬಿಲ್ಲು ಪಾವತಿ',
    titleHindi: 'नयन बैंक बिल भुगतान',
    category: 'banking',
    organization: 'Anukool Inclusive Financial Infrastructure',
    description: 'Direct accessible payment gateway for electricity, water, and essential monthly service utility bills.',
    estimatedTime: '3 minutes',
    badge: 'Banking & Utility',
    standardDenseNotice: 'Regulatory Notice: Electronic Bill Presentment & Payment (EBPP) processing is routed via NPCI BBPS nodes. Transaction settlement SLA is T+1 settlement business hours.',
    steps: [
      {
        stepNumber: 1,
        totalSteps: 3,
        title: 'Select Utility Service Type',
        titleKannada: 'ನೀವು ಪಾವತಿಸಬೇಕಾದ ಬಿಲ್ ಆಯ್ಕೆಮಾಡಿ',
        titleHindi: 'बिल का प्रकार चुनें',
        description: 'Identify service provider category for automated account ledger matching.',
        descriptionKannada: 'ನೀವು ಯಾವ ಬಿಲ್ ಕಟ್ಟಲು ಬಯಸುತ್ತೀರಿ ಎಂದು ಆಯ್ಕೆಮಾಡಿ.',
        descriptionHindi: 'आपको कौन सा बिल चुकाना है?',
        simplifiedDescription: 'Which bill do you want to pay?',
        fieldLabel: 'Utility Service Type',
        fieldLabelKannada: 'ಬಿಲ್ ಪ್ರಕಾರ',
        fieldLabelHindi: 'सेवा',
        fieldType: 'select',
        options: [
          { value: 'electricity', label: 'Electricity Bill (BESCOM/Electricity Board)', labelKannada: 'ವಿದ್ಯುತ್ ಬಿಲ್ (ಕರೆಂಟ್ ಬಿಲ್)', labelHindi: 'बिजली का बिल' },
          { value: 'water', label: 'Water Utility Bill (BWSSB/Municipal Water)', labelKannada: 'ನೀರಿನ ಬಿಲ್', labelHindi: 'पानी का बिल' },
          { value: 'cooking-gas', label: 'LPG Gas Cylinder / Pipeline Gas', labelKannada: 'ಅಡುಗೆ ಅನಿಲ (ಗ್ಯಾಸ್ ಬಿಲ್)', labelHindi: 'गैस सिलेंडर / बिल' },
        ],
        helpText: 'Select the service you wish to clear balance for.',
        audioPrompt: 'Step 1: Select the utility bill you want to pay.',
      },
      {
        stepNumber: 2,
        totalSteps: 3,
        title: 'Consumer Account Number / Meter ID',
        titleKannada: 'ಗ್ರಾಹಕ ಖಾತೆ ಸಂಖ್ಯೆ (ಆರ್‌ಆರ್ ಸಂಖ್ಯೆ / ಮೀಟರ್ ಐಡಿ)',
        titleHindi: 'उपभोक्ता नंबर / मीटर आईडी',
        description: 'Enter unique consumer alphanumeric identifier located on upper corner of physical statement.',
        descriptionKannada: 'ನಿಮ್ಮ ಕರೆಂಟ್ ಬಿಲ್‌ನಲ್ಲಿರುವ ಗ್ರಾಹಕ ಸಂಖ್ಯೆಯನ್ನು (RR Number) ನಮೂದಿಸಿ.',
        descriptionHindi: 'अपने बिजली बिल पर लिखा हुआ उपभोक्ता नंबर दर्ज करें।',
        simplifiedDescription: 'Enter your Bill Account Number.',
        fieldLabel: 'Consumer RR Number / Account ID',
        fieldLabelKannada: 'ಗ್ರಾಹಕರ ಬಿಲ್ ಸಂಖ್ಯೆ',
        fieldLabelHindi: 'उपभोक्ता नंबर',
        fieldType: 'text',
        placeholder: 'e.g. S12345678',
        helpText: 'Look at your physical bill paper for your account number.',
        audioPrompt: 'Step 2: Type your consumer account number or RR number.',
      },
      {
        stepNumber: 3,
        totalSteps: 3,
        title: 'Verify Amount & Complete Secure Pay',
        titleKannada: 'ಮೊತ್ತವನ್ನು ಪರಿಶೀಲಿಸಿ ಪಾವತಿಸಿ',
        titleHindi: 'राशि की जांच करें और भुगतान करें',
        description: 'Review fetched bill statement total and execute authorized fund deduction.',
        descriptionKannada: 'ಬಿಲ್ ಮೊತ್ತ ₹640 ಆಗಿದೆ. ಪಾವತಿಸಲು ಬಟನ್ ಒತ್ತಿ.',
        descriptionHindi: 'कुल बिल ₹640 है। भुगतान करने के लिए बटन दबाएं।',
        simplifiedDescription: 'Your bill is ₹640. Confirm to pay securely.',
        fieldLabel: 'Payment Action',
        fieldLabelKannada: 'ಪಾವತಿ ಕ್ರಮ',
        fieldLabelHindi: 'भुगतान करें',
        fieldType: 'radio',
        options: [
          { value: 'pay-upi', label: 'UPI / Direct Bank Pay (Instant)', labelKannada: 'ಯುಪಿಐ / ನೇರ ಬ್ಯಾಂಕ್ ಪಾವತಿ', labelHindi: 'यूपीआई / बैंक' },
          { value: 'pay-counter', label: 'Generate Offline Assisted Payment Token', labelKannada: 'ಆಫ್‌ಲೈನ್ ಟೋಕನ್ ಪಡೆಯಿರಿ', labelHindi: 'ऑफलाइन टोकन' }
        ],
        helpText: 'Digital receipt with BBPS transaction reference generated instantly.',
        audioPrompt: 'Step 3: Select payment method and confirm bill settlement.',
      }
    ]
  },
  {
    id: 'ration-card',
    title: 'Public Distribution System (Ration & Food Security)',
    titleKannada: 'ಪಡಿತರ ಚೀಟಿ ಮತ್ತು ಆಹಾರ ಭದ್ರತಾ ಯೋಜನೆ',
    titleHindi: 'राशन कार्ड एवं खाद्य सुरक्षा सेवा',
    category: 'government',
    organization: 'Department of Food, Civil Supplies & Consumer Affairs',
    description: 'Monthly subsidized grain entitlement quota check, family member inclusion, and digital ration card status.',
    estimatedTime: '4 minutes',
    badge: 'Social Security',
    standardDenseNotice: 'Statutory Notice: All eligible beneficiaries classified under the National Food Security Act (NFSA) Section 3 must furnish linked Aadhaar biometric seedings for monthly grain disbursement.',
    steps: [
      {
        stepNumber: 1,
        totalSteps: 3,
        title: 'Select Ration Card Service',
        titleKannada: 'ನಿಮಗೆ ಬೇಕಾದ ಪಡಿತರ ಸೇವೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
        titleHindi: 'राशन कार्ड सेवा चुनें',
        description: 'Choose required administrative action regarding your household ration card.',
        descriptionKannada: 'ನಿಮಗೆ ಯಾವ ಸೇವೆ ಬೇಕು ಎಂಬುದನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
        descriptionHindi: 'आपको कौन सी सेवा चाहिए?',
        simplifiedDescription: 'What do you want to do with your ration card?',
        fieldLabel: 'Service Type',
        fieldLabelKannada: 'ಸೇವೆಯ ಪ್ರಕಾರ',
        fieldLabelHindi: 'सेवा',
        fieldType: 'select',
        options: [
          { value: 'quota-check', label: 'Check Monthly Food Grain Quota', labelKannada: 'ಮಾಸಿಕ ಆಹಾರ ಧಾನ್ಯದ ಕೋಟಾ ಪರಿಶೀಲನೆ', labelHindi: 'मासिक राशन कोटा जांचें' },
          { value: 'add-member', label: 'Add New Family Member to Card', labelKannada: 'ಕುಟುಂಬದ ಹೊಸ ಸದಸ್ಯರನ್ನು ಸೇರಿಸಿ', labelHindi: 'नया सदस्य जोड़ें' },
          { value: 'card-status', label: 'Download Digital E-Ration Card', labelKannada: 'ಡಿಜಿಟಲ್ ರೇಷನ್ ಕಾರ್ಡ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ', labelHindi: 'डिजिटल राशन कार्ड डाउनलोड करें' }
        ],
        helpText: 'Select what you want to check or apply for today.',
        audioPrompt: 'Step 1: Select the ration card service you need.',
      },
      {
        stepNumber: 2,
        totalSteps: 3,
        title: 'Enter Ration Card Number or Aadhaar',
        titleKannada: 'ಪಡಿತರ ಚೀಟಿ ಸಂಖ್ಯೆ ಅಥವಾ ಆಧಾರ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
        titleHindi: 'राशन कार्ड नंबर या आधार नंबर दर्ज करें',
        description: 'Enter 12-digit Ration Card identifier or Head of Household Aadhaar number.',
        descriptionKannada: 'ನಿಮ್ಮ 12 ಅಂಕಿಗಳ ರೇಷನ್ ಕಾರ್ಡ್ ನಂಬರ್ ಹಾಕಿ.',
        descriptionHindi: 'अपना 12 अंकों का राशन कार्ड या आधार नंबर दर्ज करें।',
        simplifiedDescription: 'Enter your 12-digit Ration Card number.',
        fieldLabel: 'Ration / Aadhaar Number',
        fieldLabelKannada: 'ರೇಷನ್ ಕಾರ್ಡ್ ಸಂಖ್ಯೆ',
        fieldLabelHindi: 'कार्ड नंबर',
        fieldType: 'text',
        placeholder: 'e.g. 1234 5678 9012',
        helpText: 'Found on the front of your yellow/green physical ration card.',
        audioPrompt: 'Step 2: Enter your 12 digit ration card number.',
      },
      {
        stepNumber: 3,
        totalSteps: 3,
        title: 'Confirm & View Allocation',
        titleKannada: 'ದೃಢೀಕರಿಸಿ ಮತ್ತು ಕೋಟಾ ವೀಕ್ಷಿಸಿ',
        titleHindi: 'पुष्टि करें और विवरण देखें',
        description: 'Review household entitlement details and verify active fair price shop allocation.',
        descriptionKannada: 'ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ನಿಮ್ಮ ನ್ಯಾಯಬೆಲೆ ಅಂಗಡಿ ಕೋಟಾ ಪಡೆಯಿರಿ.',
        descriptionHindi: 'विवरण जांचें और कोटा देखें।',
        simplifiedDescription: 'Confirm and view your monthly food grain entitlement.',
        fieldLabel: 'Verification',
        fieldLabelKannada: 'ದೃಢೀಕರಣ',
        fieldLabelHindi: 'जांचें',
        fieldType: 'radio',
        options: [
          { value: 'view-entitlement', label: 'Fetch Official Monthly Quota & Fair Price Shop', labelKannada: 'ನನ್ನ ತಿಂಗಳ ಪಡಿತರ ಕೋಟಾ ಮತ್ತು ಅಂಗಡಿ ವಿವರ ಪಡೆಯಿರಿ', labelHindi: 'मासिक कोटा देखें' }
        ],
        helpText: 'Instantly displays authorized rice, wheat, and pulses quota.',
        audioPrompt: 'Step 3: Confirm and view your monthly ration allocation.',
      }
    ]
  }
];

export const PERSONA_PRESETS: PersonaPreset[] = [
  {
    id: 'visual-accessibility',
    name: 'Low Vision / Screen Reading',
    tagline: 'High contrast, enlarged controls, audio prompts',
    description: 'Designed for users with low vision, macular degeneration, or screen-reader preference.',
    badge: 'Visual Accessibility',
    iconName: 'Eye',
    profile: {
      textSize: 'xlarge',
      contrastTheme: 'high-contrast-dark',
      interactionMode: 'touch',
      informationMode: 'read-hear',
      cognitiveLevel: 'standard',
      language: 'en',
      motionReduction: true,
      voiceSpeed: 1.0,
      audioFeedback: true,
      actionConfirmations: true,
      buttonTargetSize: 'large',
    }
  },
  {
    id: 'cognitive-accessibility',
    name: 'Cognitive / Simple Step Mode',
    tagline: '1 question per screen, plain language, progress focus',
    description: 'Designed for users who experience sensory overload or prefer step-by-step guidance.',
    badge: 'Cognitive Focus',
    iconName: 'BrainCircuit',
    profile: {
      textSize: 'large',
      contrastTheme: 'standard',
      interactionMode: 'large-controls',
      informationMode: 'simplified',
      cognitiveLevel: 'step-by-step',
      language: 'en',
      motionReduction: true,
      voiceSpeed: 0.9,
      audioFeedback: true,
      actionConfirmations: true,
      buttonTargetSize: 'large',
    }
  },
  {
    id: 'kannada-regional',
    name: 'Kannada Native Speaker',
    tagline: 'Full Kannada translation, voice prompts & simple terms',
    description: 'Tailored for users in Karnataka who are most comfortable navigating in Kannada.',
    badge: 'Regional Language',
    iconName: 'Languages',
    profile: {
      textSize: 'large',
      contrastTheme: 'standard',
      interactionMode: 'voice',
      informationMode: 'read-hear',
      cognitiveLevel: 'step-by-step',
      language: 'kn',
      motionReduction: false,
      voiceSpeed: 0.95,
      audioFeedback: true,
      actionConfirmations: true,
      buttonTargetSize: 'standard',
    }
  },
  {
    id: 'hindi-regional',
    name: 'Hindi Native Speaker',
    tagline: 'Full Hindi translation, voice assistance & simplified language',
    description: 'Tailored for users across North & Central India who prefer Hindi voice & UI.',
    badge: 'Regional Language',
    iconName: 'Languages',
    profile: {
      textSize: 'large',
      contrastTheme: 'standard',
      interactionMode: 'voice',
      informationMode: 'read-hear',
      cognitiveLevel: 'step-by-step',
      language: 'hi',
      motionReduction: false,
      voiceSpeed: 1.0,
      audioFeedback: true,
      actionConfirmations: true,
      buttonTargetSize: 'standard',
    }
  },
  {
    id: 'motor-accessibility',
    name: 'Motor Assist / Large Targets',
    tagline: 'Extra-large 68px touch targets, dwell click, zero drag',
    description: 'Designed for users with tremors, arthritis, paralysis, or precise touch difficulties.',
    badge: 'Motor Assistance',
    iconName: 'Hand',
    profile: {
      textSize: 'xlarge',
      contrastTheme: 'warm-paper',
      interactionMode: 'large-controls',
      informationMode: 'read',
      cognitiveLevel: 'standard',
      language: 'en',
      motionReduction: true,
      voiceSpeed: 1.0,
      audioFeedback: true,
      actionConfirmations: true,
      buttonTargetSize: 'extra-large',
    }
  },
  {
    id: 'low-literacy',
    name: 'Low Digital Literacy',
    tagline: 'Audio guided, zero jargon, clear visual cues',
    description: 'Designed for first-time digital users or individuals unfamiliar with digital bureaucracy.',
    badge: 'Digital Inclusion',
    iconName: 'Sparkles',
    profile: {
      textSize: 'large',
      contrastTheme: 'standard',
      interactionMode: 'assisted',
      informationMode: 'simplified',
      cognitiveLevel: 'max-simplified',
      language: 'en',
      motionReduction: true,
      voiceSpeed: 0.85,
      audioFeedback: true,
      actionConfirmations: true,
      buttonTargetSize: 'large',
    }
  }
];

export function findServiceById(id?: string | string[]): ServiceDefinition {
  if (!id) return MOCK_SERVICES[0];
  const rawId = Array.isArray(id) ? id[0] : id;
  const cleanId = String(rawId || '').toLowerCase().trim();

  // 1. Exact match
  const exact = MOCK_SERVICES.find(s => s.id.toLowerCase() === cleanId);
  if (exact) return exact;

  // 2. Alias resolution
  if (cleanId.includes('scholarship') || cleanId.includes('education') || cleanId.includes('student') || cleanId.includes('scheme')) {
    return MOCK_SERVICES.find(s => s.id === 'government-scholarship') || MOCK_SERVICES[0];
  }
  if (cleanId.includes('hospital') || cleanId.includes('health') || cleanId.includes('doctor') || cleanId.includes('appointment') || cleanId.includes('opd') || cleanId.includes('clinic')) {
    return MOCK_SERVICES.find(s => s.id === 'hospital-appointment') || MOCK_SERVICES[1];
  }
  if (cleanId.includes('bill') || cleanId.includes('electric') || cleanId.includes('power') || cleanId.includes('banking') || cleanId.includes('utility') || cleanId.includes('pay')) {
    return MOCK_SERVICES.find(s => s.id === 'electricity-bill') || MOCK_SERVICES[2];
  }
  if (cleanId.includes('ration') || cleanId.includes('pension') || cleanId.includes('card') || cleanId.includes('food')) {
    return MOCK_SERVICES.find(s => s.id === 'ration-card') || MOCK_SERVICES[3];
  }

  return MOCK_SERVICES[0];
}

